version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    image: "amazon/dynamodb-local:1.11.477"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
