name: ci

on:
  push:
    branches:
      - main

jobs:
  build-jvm:
    runs-on: ubuntu-latest
    name: Build POC RI
    steps:
      #Run JDK configuration
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      #Gradle cache configuration
      - name: Set up Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
          run: chmod +x gradlew
      - name: Build
        run: ./gradlew build