name: ci

on:
  push:
    branches:
      - main

jobs:
  build-jvm:
    runs-on: ubuntu-latest
    name: Build POC RI
    steps:
      #Run JDK configuration
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b