name: ci
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Pipeline POC RI
    steps:
      - uses: actions/checkout@v2
      #Run JDK configuration
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --scan
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu]
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            test_features: testcontainers